### ISSUE TITLE
Make the code cleaner 

### ISSUE THREAD

**Issue by cw0x413** [sonuishaq67/42ipdiscordbot#3]
right now its spaghetti code cleaning it by making a different file and functions would be better

**Comment by PabloCorbCon** [comment]
I will like to participate in this issue, I'm developing my own discord bot, [Taur](https://github.com/PabloCorbCon/Taur) using the discord.py library.

**Comment by sonuishaq67** [comment]
Okayss ill be assigning it to you!

**Comment by PabloCorbCon** [comment]
Fine, I'm starting right now with it

**Comment by sonuishaq67** [comment]
also @PabloCorbCon you don't need to worry about the welcome.py file
Its useless and might as well be deleted

**Comment by yashqwerty1** [comment]
i will like to participate in this issue. @PabloCorbCon if you don't mind can you assign it to me please.

**Comment by PabloCorbCon** [comment]
Hey @yashqwerty1  I've already pulled, see #4. I can't assign you an issue, @cw0x413  can, I think you should talk with it.
